<?php

namespace ContainerLGLWQfF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wp2S4tSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wp2S4tS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wp2S4tS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.4Oee_pJ.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController::create' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\TaskController::create()', 'getTaskControllercreateService', true],
            'App\\Controller\\TaskController::update' => ['privates', '.service_locator.MVgLKZ8.App\\Controller\\TaskController::update()', 'getTaskControllerupdateService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.7Be6WBa.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.4Oee_pJ.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController:create' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\TaskController::create()', 'getTaskControllercreateService', true],
            'App\\Controller\\TaskController:update' => ['privates', '.service_locator.MVgLKZ8.App\\Controller\\TaskController::update()', 'getTaskControllerupdateService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.7Be6WBa.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::create' => '?',
            'App\\Controller\\TaskController::update' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:create' => '?',
            'App\\Controller\\TaskController:update' => '?',
            'App\\Controller\\TaskController:delete' => '?',
        ]);
    }
}
