<?php

namespace ContainerLGLWQfF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MVgLKZ8.App\Controller\TaskController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MVgLKZ8.App\\Controller\\TaskController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.MVgLKZ8.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.MVgLKZ8": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'task' => 'App\\Entity\\Task',
            'em' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\TaskController::update()', $container);
    }
}
